package io.github.flameyossnowy.universal.checker;

import io.github.flameyossnowy.universal.api.annotations.Condition;
import io.github.flameyossnowy.universal.api.annotations.OnDelete;
import io.github.flameyossnowy.universal.api.annotations.OnUpdate;
import io.github.flameyossnowy.universal.api.annotations.enums.Consistency;
import io.github.flameyossnowy.universal.api.meta.JsonIndexModel;
import io.github.flameyossnowy.universal.api.meta.JsonStorageKind;
import io.github.flameyossnowy.universal.api.meta.RelationshipKind;
import io.github.flameyossnowy.universal.checker.processor.TypeMirrorUtils;

import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;

import java.util.List;

public record FieldModel(
    String name,
    String columnName,
    TypeMirror type,
    String typeQualifiedName,
    boolean id,
    boolean autoIncrement,
    boolean nullable,
    boolean relationship,
    RelationshipKind relationshipKind,
    Consistency consistency,
    String getterName,
    String setterName,
    boolean lazy,
    boolean insertable,
    boolean updatable,
    boolean hasNowAnnotation,
    boolean hasBinaryAnnotation,
    boolean hasUniqueAnnotation,
    String defaultValue,
    String defaultValueProviderClass,
    boolean enumAsOrdinal,
    String externalRepository,
    Condition condition,
    OnDelete onDelete,
    OnUpdate onUpdate,
    String resolveWithClass,

    TypeMirror elementType,      // for collection or generic field
    TypeMirror mapKeyType,       // if Map, the key type
    TypeMirror mapValueType,     // if Map, the value type
    boolean indexed,            // explicitly marked as indexed
    CollectionKind collectionKind,

    boolean isJson,
    JsonStorageKind jsonStorageKind,
    String jsonColumnDefinition,
    String jsonCodecClass,
    boolean jsonQueryable,
    boolean jsonPartialUpdate,
    List<JsonIndexModel> jsonIndexes
) {
    /**
     * Determines if this field participates in entity construction.
     *
     * Fields that do NOT participate:
     * - Relationship fields (loaded separately)
     * - Auto-increment fields (generated by database)
     * - Collection/Map/Array fields that are not relationships (loaded separately)
     *
     * @return true if the field should be included in construction
     */
    public boolean participatesInConstruction() {
        return !relationship && !autoIncrement;
    }

    public boolean isNotCollection(Types types, Elements elements) {
        return !TypeMirrorUtils.isCollection(types, elements, type) &&
            !TypeMirrorUtils.isMap(types, elements, type) &&
            !TypeMirrorUtils.isArray(type);
    }

    public boolean notIndexed() {
        return !indexed;
    }
}
