package io.github.flameyossnowy.universal.api.factory;

import io.github.flameyossnowy.universal.api.params.DatabaseParameters;

/**
 * Factory interface for constructing, populating, and persisting entities.
 * <p>
 * This interface provides compile-time generated implementations that handle:
 * <ul>
 *   <li>Entity construction from database result sets</li>
 *   <li>Relationship population (lazy and eager)</li>
 *   <li>Entity insertion into the database</li>
 *   <li>Collection field persistence</li>
 * </ul>
 *
 * @param <T>  The entity type
 * @param <ID> The primary key type
 */
public interface ObjectModel<T, ID> {

    /**
     * Constructs a new entity instance from a ValueReader.
     * <p>
     * This method reads scalar fields from the ValueReader and populates
     * a new entity instance. Relationship fields are not populated by this
     * method - use {@link #populateRelationships} for that.
     *
     * @param reader The value reader containing field data from the database
     * @return A new entity instance with scalar fields populated
     */
    T construct(ValueReader reader);

    /**
     * Populates relationship fields of an entity after construction.
     * <p>
     * This method is called after the entity has been constructed and should
     * populate all relationship fields (OneToOne, OneToMany, ManyToOne) using
     * the provided RelationshipLoader.
     *
     * @param entity The entity whose relationships should be populated
     * @param id     The primary key of the entity
     * @param loader The relationship loader to use for fetching related entities
     */
    void populateRelationships(T entity, ID id, RelationshipLoader loader);

    /**
     * Inserts a single entity into the database.
     * <p>
     * This method binds all insertable scalar fields and relationship foreign keys
     * to the provided DatabaseParameters. It does NOT insert collection fields
     * (List, Set, Map, arrays) - those are handled by {@link #insertCollectionEntities}.
     * <p>
     * Fields that are skipped:
     * <ul>
     *   <li>Auto-increment fields (generated by database)</li>
     *   <li>Non-insertable fields (marked as insertable=false)</li>
     *   <li>OneToMany relationships (inverse side)</li>
     *   <li>Collection/Map/Array fields (handled separately)</li>
     * </ul>
     * <p>
     * For OneToOne and ManyToOne relationships, this method extracts the primary
     * key value from the related entity and inserts it as a foreign key.
     *
     * @param statement The database parameters to bind values to
     * @param entity    The entity to insert
     * @throws Exception If an error occurs during insertion
     */
    void insertEntity(DatabaseParameters statement, T entity) throws Exception;

    /**
     * Inserts all collection fields of an entity after the primary entity has been inserted.
     * <p>
     * This method is called after {@link #insertEntity} has completed and the entity's
     * primary key has been generated/set. It handles:
     * <ul>
     *   <li>List and Set fields (via SQLCollections)</li>
     *   <li>Map fields (via SQLCollections)</li>
     *   <li>Array fields</li>
     * </ul>
     * <p>
     * Collection fields that represent relationships (e.g., {@code @OneToMany List<Child>})
     * are typically not inserted here, as they are the inverse side of the relationship.
     *
     * @param entity    The entity whose collection fields should be inserted
     * @param id        The primary key of the entity
     * @param statement The database parameters (maybe used for batch operations)
     * @throws Exception If an error occurs during collection insertion
     */
    void insertCollectionEntities(T entity, ID id, DatabaseParameters statement) throws Exception;

    /**
     * Returns the runtime Class object for the primary key type.
     * <p>
     * This is useful for generic type operations and reflection-based operations
     * that need to know the concrete ID type at runtime.
     *
     * @return The Class object representing the ID type
     */
    Class<ID> getIdType();

    /**
     * Returns the runtime Class object for the entity type.
     * <p>
     * This is useful for generic type operations and reflection-based operations
     * that need to know the concrete entity type at runtime.
     *
     * @return The Class object representing the entity type
     */
    Class<T> getEntityType();

    ID getId(T entity);
}